/**
 * BrickLink color catalog snapshot.
 * Source semantics: BrickLink Color resource (id, name, HTML color code, type).
 * Snapshot synchronized 2026-07-21T22:27:02.196Z.
 */
export const bricklinkColors = [
  { id: 1, name: "White", hex: "#F9F7F1", type: "Solid" },
  { id: 2, name: "Tan", hex: "#EED9A4", type: "Solid" },
  { id: 3, name: "Yellow", hex: "#FFE001", type: "Solid" },
  { id: 4, name: "Orange", hex: "#FF8901", type: "Solid" },
  { id: 5, name: "Red", hex: "#DB2A1A", type: "Solid" },
  { id: 6, name: "Green", hex: "#009D48", type: "Solid" },
  { id: 7, name: "Blue", hex: "#0066CA", type: "Solid" },
  { id: 8, name: "Brown", hex: "#70462E", type: "Solid" },
  { id: 9, name: "Light Gray", hex: "#C2BFB0", type: "Solid" },
  { id: 10, name: "Dark Gray", hex: "#7E7563", type: "Solid" },
  { id: 11, name: "Black", hex: "#212121", type: "Solid" },
  { id: 12, name: "Trans-Clear", hex: "#EEEEEE", type: "Transparent" },
  { id: 13, name: "Trans-Brown", hex: "#939484", type: "Transparent" },
  { id: 14, name: "Trans-Dark Blue", hex: "#00296B", type: "Transparent" },
  { id: 15, name: "Trans-Light Blue", hex: "#68BCC5", type: "Transparent" },
  { id: 16, name: "Trans-Neon Green", hex: "#C0F500", type: "Transparent" },
  { id: 17, name: "Trans-Red", hex: "#9C0010", type: "Transparent" },
  { id: 18, name: "Trans-Neon Orange", hex: "#FF4231", type: "Transparent" },
  { id: 19, name: "Trans-Yellow", hex: "#EBF72D", type: "Transparent" },
  { id: 20, name: "Trans-Green", hex: "#217625", type: "Transparent" },
  { id: 21, name: "Chrome Gold", hex: "#F1F2E1", type: "Chrome" },
  { id: 22, name: "Chrome Silver", hex: "#DCDCDC", type: "Chrome" },
  { id: 23, name: "Pink", hex: "#F5CDD6", type: "Solid" },
  { id: 24, name: "Purple", hex: "#7A238D", type: "Solid" },
  { id: 25, name: "Salmon", hex: "#FF7D5D", type: "Solid" },
  { id: 26, name: "Light Salmon", hex: "#FCC7B7", type: "Solid" },
  { id: 27, name: "Rust", hex: "#B24817", type: "Solid" },
  { id: 28, name: "Nougat", hex: "#FFAF7D", type: "Solid" },
  { id: 29, name: "Earth Orange", hex: "#E6881D", type: "Solid" },
  { id: 31, name: "Medium Orange", hex: "#FFA531", type: "Solid" },
  { id: 32, name: "Light Orange", hex: "#FFBC36", type: "Solid" },
  { id: 33, name: "Light Yellow", hex: "#FEE89F", type: "Solid" },
  { id: 34, name: "Lime", hex: "#C4E000", type: "Solid" },
  { id: 35, name: "Light Lime", hex: "#ECEEBD", type: "Solid" },
  { id: 36, name: "Bright Green", hex: "#10CB31", type: "Solid" },
  { id: 37, name: "Medium Green", hex: "#91DF8C", type: "Solid" },
  { id: 38, name: "Light Green", hex: "#D7EED1", type: "Solid" },
  { id: 39, name: "Dark Turquoise", hex: "#00A29F", type: "Solid" },
  { id: 40, name: "Light Turquoise", hex: "#00C5BC", type: "Solid" },
  { id: 41, name: "Aqua", hex: "#BCE5DC", type: "Solid" },
  { id: 42, name: "Medium Blue", hex: "#84B0DD", type: "Solid" },
  { id: 43, name: "Violet", hex: "#3448A4", type: "Solid" },
  { id: 44, name: "Light Violet", hex: "#C9CAE2", type: "Solid" },
  { id: 46, name: "Glow In Dark Opaque", hex: "#D4D5C9", type: "Milky" },
  { id: 47, name: "Dark Pink", hex: "#EF5BB3", type: "Solid" },
  { id: 48, name: "Sand Green", hex: "#A2BFA3", type: "Solid" },
  { id: 49, name: "Very Light Gray", hex: "#E6E1D5", type: "Solid" },
  { id: 50, name: "Trans-Dark Pink", hex: "#CE1D9B", type: "Transparent" },
  { id: 51, name: "Trans-Purple", hex: "#5525B7", type: "Transparent" },
  { id: 52, name: "Chrome Blue", hex: "#5C66A4", type: "Chrome" },
  { id: 54, name: "Sand Purple", hex: "#BC9CAF", type: "Solid" },
  { id: 55, name: "Sand Blue", hex: "#8899AB", type: "Solid" },
  { id: 56, name: "Rose Pink", hex: "#F2D3D1", type: "Solid" },
  { id: 57, name: "Chrome Antique Brass", hex: "#645A4C", type: "Chrome" },
  { id: 58, name: "Sand Red", hex: "#C58D80", type: "Solid" },
  { id: 59, name: "Dark Red", hex: "#8B2826", type: "Solid" },
  { id: 60, name: "Milky White", hex: "#D4D3DD", type: "Milky" },
  { id: 61, name: "Pearl Light Gold", hex: "#E7AE5A", type: "Pearl" },
  { id: 62, name: "Light Blue", hex: "#C8D9E1", type: "Solid" },
  { id: 63, name: "Dark Blue", hex: "#243757", type: "Solid" },
  { id: 64, name: "Chrome Green", hex: "#3CB371", type: "Chrome" },
  { id: 65, name: "Metallic Gold", hex: "#B8860B", type: "Metallic" },
  { id: 66, name: "Pearl Light Gray", hex: "#ACB7C0", type: "Pearl" },
  { id: 67, name: "Metallic Silver", hex: "#C0C0C0", type: "Metallic" },
  { id: 68, name: "Dark Orange", hex: "#B35408", type: "Solid" },
  { id: 69, name: "Dark Tan", hex: "#B89869", type: "Solid" },
  { id: 70, name: "Metallic Green", hex: "#BDB573", type: "Metallic" },
  { id: 71, name: "Magenta", hex: "#B72276", type: "Solid" },
  { id: 72, name: "Maersk Blue", hex: "#7DC1D8", type: "Solid" },
  { id: 73, name: "Medium Violet", hex: "#9391E4", type: "Solid" },
  { id: 74, name: "Trans-Medium Blue", hex: "#76A3C8", type: "Transparent" },
  { id: 76, name: "Medium Lime", hex: "#DFE000", type: "Solid" },
  { id: 77, name: "Pearl Dark Gray", hex: "#666660", type: "Pearl" },
  { id: 78, name: "Pearl Sand Blue", hex: "#868FAA", type: "Pearl" },
  { id: 80, name: "Dark Green", hex: "#2E5543", type: "Solid" },
  { id: 81, name: "Flat Dark Gold", hex: "#AD7118", type: "Pearl" },
  { id: 82, name: "Chrome Pink", hex: "#AA4D8E", type: "Chrome" },
  { id: 83, name: "Pearl White", hex: "#FFFFFF", type: "Pearl" },
  { id: 84, name: "Copper", hex: "#AC6D52", type: "Pearl" },
  { id: 85, name: "Dark Bluish Gray", hex: "#7D7C78", type: "Solid" },
  { id: 86, name: "Light Bluish Gray", hex: "#BFBEBA", type: "Solid" },
  { id: 87, name: "Sky Blue", hex: "#8AD4E1", type: "Solid" },
  { id: 88, name: "Reddish Brown", hex: "#82422A", type: "Solid" },
  { id: 89, name: "Dark Purple", hex: "#6438A9", type: "Solid" },
  { id: 90, name: "Light Nougat", hex: "#FAD3B2", type: "Solid" },
  { id: 91, name: "Light Brown", hex: "#99663E", type: "Solid" },
  { id: 93, name: "Light Purple", hex: "#AF3195", type: "Solid" },
  { id: 94, name: "Medium Dark Pink", hex: "#EDA1AE", type: "Solid" },
  { id: 95, name: "Flat Silver", hex: "#8D949C", type: "Pearl" },
  { id: 96, name: "Very Light Orange", hex: "#FFDCA4", type: "Solid" },
  { id: 97, name: "Royal Blue (Old Blue-Violet)", hex: "#506CEF", type: "Solid" },
  { id: 98, name: "Trans-Orange", hex: "#E96F01", type: "Transparent" },
  { id: 99, name: "Very Light Bluish Gray", hex: "#E7E6E2", type: "Solid" },
  { id: 100, name: "Glitter Trans-Dark Pink", hex: "#CE1D9B", type: "Glitter" },
  { id: 101, name: "Glitter Trans-Clear", hex: "#EEEEEE", type: "Glitter" },
  { id: 102, name: "Glitter Trans-Purple", hex: "#3A2B82", type: "Glitter" },
  { id: 103, name: "Bright Light Yellow", hex: "#FFF08C", type: "Solid" },
  { id: 104, name: "Bright Pink", hex: "#F8BDDB", type: "Solid" },
  { id: 105, name: "Bright Light Blue", hex: "#BADBFE", type: "Solid" },
  { id: 106, name: "Fabuland Brown", hex: "#B3694E", type: "Solid" },
  { id: 107, name: "Trans-Pink", hex: "#FF8298", type: "Transparent" },
  { id: 108, name: "Trans-Bright Green", hex: "#10CB31", type: "Transparent" },
  { id: 109, name: "Dark Royal Blue", hex: "#2032B0", type: "Solid" },
  { id: 110, name: "Bright Light Orange", hex: "#FFC700", type: "Solid" },
  { id: 111, name: "Speckle Black-Silver", hex: "#7C7E7C", type: "Speckle" },
  { id: 113, name: "Trans-Aqua", hex: "#B7C8BF", type: "Transparent" },
  { id: 114, name: "Trans-Light Purple", hex: "#B97AB1", type: "Transparent" },
  { id: 115, name: "Pearl Gold", hex: "#E79E1D", type: "Pearl" },
  { id: 116, name: "Speckle Black-Copper", hex: "#5F4E47", type: "Speckle" },
  { id: 117, name: "Speckle DBGray-Silver", hex: "#4A6363", type: "Speckle" },
  { id: 118, name: "Glow In Dark Trans", hex: "#BDC6AD", type: "Milky" },
  { id: 119, name: "Pearl Very Light Gray", hex: "#D4D2CD", type: "Pearl" },
  { id: 120, name: "Dark Brown", hex: "#50372F", type: "Solid" },
  { id: 121, name: "Trans-Neon Yellow", hex: "#FFD700", type: "Transparent" },
  { id: 122, name: "Chrome Black", hex: "#544E4F", type: "Chrome" },
  { id: 123, name: "Mx White", hex: "#F2EDE5", type: "Modulex" },
  { id: 124, name: "Mx Light Bluish Gray", hex: "#BDBDB8", type: "Modulex" },
  { id: 125, name: "Mx Light Gray", hex: "#C6C8C3", type: "Modulex" },
  { id: 126, name: "Mx Charcoal Gray", hex: "#534E4A", type: "Modulex" },
  { id: 127, name: "Mx Tile Gray", hex: "#A19A8F", type: "Modulex" },
  { id: 128, name: "Mx Black", hex: "#322D29", type: "Modulex" },
  { id: 129, name: "Mx Red", hex: "#E04F32", type: "Modulex" },
  { id: 130, name: "Mx Pink Red", hex: "#FB9392", type: "Modulex" },
  { id: 131, name: "Mx Tile Brown", hex: "#5A4238", type: "Modulex" },
  { id: 132, name: "Mx Brown", hex: "#9C7C4F", type: "Modulex" },
  { id: 133, name: "Mx Buff", hex: "#EED9A4", type: "Modulex" },
  { id: 134, name: "Mx Terracotta", hex: "#B66A4B", type: "Modulex" },
  { id: 135, name: "Mx Orange", hex: "#F58D26", type: "Modulex" },
  { id: 136, name: "Mx Light Orange", hex: "#FFB647", type: "Modulex" },
  { id: 137, name: "Mx Light Yellow", hex: "#F8E469", type: "Modulex" },
  { id: 138, name: "Mx Ochre Yellow", hex: "#E5C230", type: "Modulex" },
  { id: 139, name: "Mx Lemon", hex: "#F1E145", type: "Modulex" },
  { id: 140, name: "Mx Olive Green", hex: "#8FA05A", type: "Modulex" },
  { id: 141, name: "Mx Pastel Green", hex: "#B1D52C", type: "Modulex" },
  { id: 142, name: "Mx Aqua Green", hex: "#75DBB6", type: "Modulex" },
  { id: 143, name: "Mx Tile Blue", hex: "#0046A5", type: "Modulex" },
  { id: 144, name: "Mx Medium Blue", hex: "#75A2CC", type: "Modulex" },
  { id: 145, name: "Mx Pastel Blue", hex: "#7DC1D8", type: "Modulex" },
  { id: 146, name: "Mx Teal Blue", hex: "#4C7D89", type: "Modulex" },
  { id: 147, name: "Mx Violet", hex: "#BE9BC5", type: "Modulex" },
  { id: 148, name: "Mx Pink", hex: "#EDA1AE", type: "Modulex" },
  { id: 149, name: "Mx Clear", hex: "#EEEEEE", type: "Modulex" },
  { id: 150, name: "Medium Nougat", hex: "#E3A05B", type: "Solid" },
  { id: 151, name: "Speckle Black-Gold", hex: "#AB9421", type: "Speckle" },
  { id: 152, name: "Light Aqua", hex: "#CFEFEA", type: "Solid" },
  { id: 153, name: "Dark Azure", hex: "#009FE0", type: "Solid" },
  { id: 154, name: "Lavender", hex: "#D3BDE3", type: "Solid" },
  { id: 155, name: "Olive Green", hex: "#ABA953", type: "Solid" },
  { id: 156, name: "Medium Azure", hex: "#6ACEE0", type: "Solid" },
  { id: 157, name: "Medium Lavender", hex: "#C689D9", type: "Solid" },
  { id: 158, name: "Yellowish Green", hex: "#E7F2A7", type: "Solid" },
  { id: 159, name: "Glow In Dark White", hex: "#D9D9D9", type: "Milky" },
  { id: 160, name: "Fabuland Orange", hex: "#EF9121", type: "Solid" },
  { id: 161, name: "Dark Yellow", hex: "#DD982E", type: "Solid" },
  { id: 162, name: "Glitter Trans-Light Blue", hex: "#68BCC5", type: "Glitter" },
  { id: 163, name: "Glitter Trans-Neon Green", hex: "#C0F500", type: "Glitter" },
  { id: 164, name: "Trans-Light Orange", hex: "#E99A3A", type: "Transparent" },
  { id: 165, name: "Neon Orange", hex: "#FA5947", type: "Solid" },
  { id: 166, name: "Neon Green", hex: "#DBF355", type: "Solid" },
  { id: 167, name: "Reddish Orange", hex: "#FF5500", type: "Solid" },
  { id: 168, name: "Umber", hex: "#735442", type: "Solid" },
  { id: 169, name: "Sienna", hex: "#EA8339", type: "Solid" },
  { id: 170, name: "Satin Trans-Yellow", hex: "#EBF72D", type: "Satin" },
  { id: 171, name: "Lemon", hex: "#EDDC44", type: "Solid" },
  { id: 172, name: "Warm Yellowish Orange", hex: "#FFD788", type: "Solid" },
  { id: 173, name: "Ochre Yellow", hex: "#D89905", type: "Solid" },
  { id: 174, name: "Blue Violet", hex: "#5D67B4", type: "Solid" },
  { id: 175, name: "Warm Pink", hex: "#F6C6BD", type: "Solid" },
  { id: 210, name: "Mx Foil Dark Gray", hex: "#948F84", type: "Modulex" },
  { id: 211, name: "Mx Foil Light Gray", hex: "#D1CDBD", type: "Modulex" },
  { id: 212, name: "Mx Foil Dark Green", hex: "#5E734E", type: "Modulex" },
  { id: 213, name: "Mx Foil Light Green", hex: "#B3C068", type: "Modulex" },
  { id: 214, name: "Mx Foil Dark Blue", hex: "#4B8AA4", type: "Modulex" },
  { id: 215, name: "Mx Foil Light Blue", hex: "#83A7A9", type: "Modulex" },
  { id: 216, name: "Mx Foil Violet", hex: "#8B6E82", type: "Modulex" },
  { id: 217, name: "Mx Foil Red", hex: "#BB5D51", type: "Modulex" },
  { id: 218, name: "Mx Foil Yellow", hex: "#FFEE77", type: "Modulex" },
  { id: 219, name: "Mx Foil Orange", hex: "#FB9D2B", type: "Modulex" },
  { id: 220, name: "Coral", hex: "#FF8172", type: "Solid" },
  { id: 221, name: "Trans-Light Green", hex: "#94E5AB", type: "Transparent" },
  { id: 222, name: "Glitter Trans-Orange", hex: "#D04010", type: "Glitter" },
  { id: 223, name: "Satin Trans-Light Blue", hex: "#68BCC5", type: "Satin" },
  { id: 224, name: "Satin Trans-Dark Pink", hex: "#CE1D9B", type: "Satin" },
  { id: 225, name: "Dark Nougat", hex: "#CE7942", type: "Solid" },
  { id: 226, name: "Trans-Light Bright Green", hex: "#71EB54", type: "Transparent" },
  { id: 227, name: "Clikits Lavender", hex: "#E0AAD9", type: "Solid" },
  { id: 228, name: "Satin Trans-Clear", hex: "#EEEEEE", type: "Satin" },
  { id: 229, name: "Satin Trans-Brown", hex: "#939484", type: "Satin" },
  { id: 230, name: "Satin Trans-Purple", hex: "#8320B7", type: "Satin" },
  { id: 231, name: "Dark Salmon", hex: "#FF6326", type: "Solid" },
  { id: 232, name: "Satin Trans-Dark Blue", hex: "#1552E2", type: "Satin" },
  { id: 233, name: "Satin Trans-Bright Green", hex: "#7FE15B", type: "Satin" },
  { id: 234, name: "Trans-Medium Purple", hex: "#9C41B6", type: "Transparent" },
  { id: 235, name: "Reddish Gold", hex: "#E7891B", type: "Pearl" },
  { id: 236, name: "Neon Yellow", hex: "#FFFC00", type: "Solid" },
  { id: 237, name: "Bionicle Copper", hex: "#985750", type: "Pearl" },
  { id: 238, name: "Bionicle Gold", hex: "#B9752F", type: "Pearl" },
  { id: 239, name: "Bionicle Silver", hex: "#A59287", type: "Pearl" },
  { id: 240, name: "Medium Brown", hex: "#A16C42", type: "Solid" },
  { id: 241, name: "Medium Tan", hex: "#FBC685", type: "Solid" },
  { id: 242, name: "Dark Olive Green", hex: "#76753F", type: "Solid" },
  { id: 243, name: "Pearl Sand Purple", hex: "#B5A1BA", type: "Pearl" },
  { id: 244, name: "Pearl Black", hex: "#282725", type: "Pearl" },
  { id: 245, name: "Lilac", hex: "#7862CE", type: "Solid" },
  { id: 246, name: "Light Lilac", hex: "#CDCCEE", type: "Solid" },
  { id: 247, name: "Little Robots Blue", hex: "#5DBFE4", type: "Solid" },
  { id: 248, name: "Fabuland Lime", hex: "#ADD237", type: "Solid" },
  { id: 249, name: "Reddish Copper", hex: "#D06926", type: "Pearl" },
  { id: 250, name: "Metallic Copper", hex: "#C58259", type: "Metallic" },
  { id: 251, name: "Trans-Black", hex: "#777777", type: "Transparent" },
  { id: 252, name: "Pearl Red", hex: "#E54952", type: "Pearl" },
  { id: 253, name: "Pearl Green", hex: "#13A452", type: "Pearl" },
  { id: 254, name: "Pearl Blue", hex: "#3977C7", type: "Pearl" },
  { id: 255, name: "Pearl Brown", hex: "#815542", type: "Pearl" },
] as const;

export type BricklinkColor = (typeof bricklinkColors)[number];
